services:
  web:
    restart: unless-stopped
    image: devclubwmu/devclub-prod:webdev-landing
    container_name: webdev-landing-prod
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      NEXTAUTH_URL: https://devwmu.com
    secrets:
      - deploy_id
      - webapp_url
      - nextauth_secret
      - discord_auth_id
      - discord_auth_secret
      - db_url
    networks:
      - devnet
networks:
  devnet:
    external: true

secrets:
  deploy_id:
    file: ./secrets/deploy_id.txt
  webapp_url:
    file: ./secrets/webapp_url.txt
  nextauth_secret:
    file: ./secrets/nextauth_secret.txt
  discord_auth_id:
    file: ./secrets/discord_auth_id.txt
  discord_auth_secret:
    file: ./secrets/discord_auth_secret.txt
  db_url:
    file: ./secrets/db_url.txt
