import type { LeadStatus, PipelineCellProps } from "@/models";

export const pipelineDeals: PipelineCellProps[] = [
  {
    ID: "1",
    title: "Website Redesign",
    description: "Full revamp for e-commerce platform",
    capital: "$15,000",
    leadName: "Alice Thompson",
    companyName: "Bluewave Digital",
    avatarURL: "https://placehold.co/40x40/4A90E2/FFFFFF.webp?text=AT",
    addedOn: new Date("2025-04-01"),
    dueDate: new Date("2025-05-01"),
    status: "working",
    leadType: "individual",
    isDragging: false,
  },
  {
    ID: "2",
    title: "AI Lead Scoring Integration",
    description: "Machine learning model proposal",
    capital: "$7,200",
    leadName: "John Rivera",
    companyName: "NeuralCore Labs",
    avatarURL: "https://placehold.co/40x40/00C896/FFFFFF.webp?text=JR",
    addedOn: new Date("2025-03-25"),
    dueDate: new Date("2025-04-20"),
    status: "qualified",
    leadType: "partner",
    isDragging: false,
  },
  {
    ID: "3",
    title: "Cloud Migration",
    description: "Enterprise data platform migration",
    capital: "$32,000",
    leadName: "Mei Lin",
    companyName: "SkyNet Solutions",
    avatarURL: "https://placehold.co/40x40/FF9800/FFFFFF.webp?text=ML",
    addedOn: new Date("2025-02-15"),
    dueDate: new Date("2025-04-15"),
    status: "working",
    leadType: "vendor",
    isDragging: false,
  },
  {
    ID: "4",
    title: "Prospecting Call",
    description: "Initial outreach call scheduled",
    capital: "$0",
    leadName: "Bryan Kim",
    companyName: "Elevate Agency",
    avatarURL: "https://placehold.co/40x40/673AB7/FFFFFF.webp?text=BK",
    addedOn: new Date("2025-04-10"),
    dueDate: new Date("2025-05-01"),
    status: "new",
    leadType: "customer",
    isDragging: false,
  },
  {
    ID: "5",
    title: "UX Overhaul Pitch",
    description: "Waiting on proposal approval",
    capital: "$5,500",
    leadName: "Samantha Voss",
    companyName: "PixelPond",
    avatarURL: "https://placehold.co/40x40/E91E63/FFFFFF.webp?text=SV",
    addedOn: new Date("2025-03-18"),
    dueDate: new Date("2025-04-30"),
    status: "proposal",
    leadType: "individual",
    isDragging: false,
  },
  {
    ID: "6",
    title: "Security Audit",
    description: "Mid-negotiation over scope and terms",
    capital: "$11,200",
    leadName: "Carlos Mendes",
    companyName: "SecureLayer",
    avatarURL: "https://placehold.co/40x40/009688/FFFFFF.webp?text=CM",
    addedOn: new Date("2025-02-28"),
    dueDate: new Date("2025-04-25"),
    status: "negotiation",
    leadType: "vendor",
    isDragging: false,
  },
  {
    ID: "7",
    title: "Annual Service Contract",
    description: "Deal closed and signed",
    capital: "$20,000",
    leadName: "Rachel Ng",
    companyName: "Orbital Tech",
    avatarURL: "https://placehold.co/40x40/03A9F4/FFFFFF.webp?text=RN",
    addedOn: new Date("2025-01-20"),
    dueDate: new Date("2025-03-01"),
    status: "closed_won",
    leadType: "customer",
    isDragging: false,
  },
  {
    ID: "8",
    title: "Custom Analytics Platform",
    description: "Client dropped out mid-negotiation",
    capital: "$18,000",
    leadName: "Liam Shah",
    companyName: "InsightIQ",
    avatarURL: "https://placehold.co/40x40/F44336/FFFFFF.webp?text=LS",
    addedOn: new Date("2025-02-10"),
    dueDate: new Date("2025-03-20"),
    status: "closed_lost",
    leadType: "customer",
    isDragging: false,
  },
];

export const pipelineStages: { status: LeadStatus; title: string }[] = [
  { status: "new", title: "New" },
  { status: "working", title: "Working" },
  { status: "qualified", title: "Qualified" },
  { status: "proposal", title: "Proposal Sent" },
  { status: "negotiation", title: "Negotiation" },
  { status: "closed_won", title: "Won" },
  { status: "closed_lost", title: "Lost" },
];
