name: Build and Push Docker Image

on:
  push:
    branches: ["staging"]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASS_TOKEN }}

      - name: Generate dummy env
        run: |
          echo "NEXTAUTH_SECRET=dummy" >> .env.local
          echo "NEXTAUTH_URL=http://localhost:3000" >> .env.local
          echo "AUTH_DISCORD_ID=dummy" >> .env.local
          echo "AUTH_DISCORD_SECRET=dummy" >> .env.local
          echo "DATABASE_URL=postgresql://user:pass@localhost:5432/db" >> .env.local

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            devclubwmu/devclub-prod:webdev-landing
            devclubwmu/devclub-prod:${{ github.sha }}
