name: Deploy

on:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    branches: ["staging"]
    types:
      - completed

  push:
    branches: ["production"]

jobs:
  deploy-staging:
    if: github.event_name == 'workflow_run'
    runs-on: ["self-hosted", "staging"]
    steps:
      - name: Run staging deployment script
        run: DEPLOY_ENV=staging /home/webdev/webdev-landing/deploy-staging.sh

  deploy-prod:
    if: github.ref == 'refs/heads/production'
    runs-on: ["self-hosted", "prod"]
    steps:
      - name: Run production deployment script
        run: DEPLOY_ENV=production /home/webdev/webdev-landing/deploy.sh
