name: Deploy

on:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Run deployment script
        run: /home/webdev/webdev-landing/deploy.sh
